version: "3.1"
services:

    mysql:
      image: mysql:8.0
      container_name: smarty-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=smarty
        - MYSQL_DATABASE=smarty
        - MYSQL_USER=smarty
        - MYSQL_PASSWORD=smarty
      ports:
        - "9092:3306"

    webserver:
      image: nginx:alpine
      container_name: smarty-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "9090:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: smarty-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
